#############################################################################
# Makefile for building: Burner
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Mar 1 11:23:14 2012
# Project:  Burner.pro
# Template: app
# Command: /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/bin/qmake -o Makefile Burner.pro
#############################################################################

####### Compiler, tools and options

CC            = qcc -Vgcc_ntoarmv7le
CXX           = qcc -Vgcc_ntoarmv7le -lang-c++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/unsupported/blackberry-armv7le-g++ -I. -I../Qt/stage/nto/usr/include/qt4/QtCore -I../Qt/stage/nto/usr/include/qt4/QtGui -I../Qt/stage/nto/usr/include/qt4 -Iinclude -I. -I../Qt/stage/nto/usr/include -I/home/xitij/Development/Qt/stage/nto/usr/include/freetype2
LINK          = qcc -Vgcc_ntoarmv7le -lang-c++
LFLAGS        = -Wl,-rpath-link,/home/xitij/Development/Qt/stage/nto/armle-v7/lib -Wl,-rpath-link,/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib -Wl,-rpath,'./app/native/lib' -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/xitij/Development/Qt/stage/nto/armle-v7/lib -L/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib -L/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib -lQtGui -L/opt/bbndk-2.0.0/target/qnx6/armle-v7/usr/lib -L/opt/bbndk-2.0.0/target/qnx6/armle-v7/lib -L/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib -L/home/xitij/Development/Qt/stage/nto/armle-v7/lib -L/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib -lQtCore -lm 
AR            = ntoarmv7-ar cqs
RANLIB        = ntoarmv7-ranlib
QMAKE         = /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = ntoarmv7-strip
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/widget.cpp \
		src/Burner.cpp moc_Burner.cpp \
		moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		Burner.o \
		moc_Burner.o \
		moc_widget.o
DIST          = ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		Burner.pro
QMAKE_TARGET  = Burner
DESTDIR       = 
TARGET        = Burner

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Burner.pro  ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/unsupported/blackberry-armv7le-g++/qmake.conf ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtGui.prl \
		/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtCore.prl
	$(QMAKE) -o Makefile Burner.pro
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtGui.prl:
/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Burner.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Burner1.0.0 || $(MKDIR) .tmp/Burner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Burner1.0.0/ && $(COPY_FILE) --parents include/Burner.h include/widget.h .tmp/Burner1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/widget.cpp src/Burner.cpp .tmp/Burner1.0.0/ && (cd `dirname .tmp/Burner1.0.0` && $(TAR) Burner1.0.0.tar Burner1.0.0 && $(COMPRESS) Burner1.0.0.tar) && $(MOVE) `dirname .tmp/Burner1.0.0`/Burner1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Burner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


Burner.bar: Burner
	blackberry-nativepackager -devMode -debugToken ~/debugToken.bar -package Burner.bar -arg -platform -arg blackberry blackberry-tablet.xml Burner -e res/icon.png res/icon.png -e res/splashscreen.png res/splashscreen.png -e /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtCore.so.4 lib/libQtCore.so.4 -e /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtGui.so.4 lib/libQtGui.so.4 -e /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtOpenGL.so.4 lib/libQtOpenGL.so.4 -e /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtNetwork.so.4 lib/libQtNetwork.so.4 -e /home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/plugins/platforms/libblackberry.so lib/platforms/libblackberry.so

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Burner.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Burner.cpp moc_widget.cpp
moc_Burner.cpp: include/widget.h \
		include/Burner.h
	/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) -D__QNXNTO__ include/Burner.h -o moc_Burner.cpp

moc_widget.cpp: include/widget.h
	/home/xitij/Development/Qt/stage/nto/armle-v7/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) -D__QNXNTO__ include/widget.h -o moc_widget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

widget.o: src/widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o src/widget.cpp

Burner.o: src/Burner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Burner.o src/Burner.cpp

moc_Burner.o: moc_Burner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Burner.o moc_Burner.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

